//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "auto_role_group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auto_role::Entity")]
    AutoRole,
}

impl Related<super::auto_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AutoRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
