//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "auto_role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id:    String,
    pub group: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::auto_role_group::Entity",
        from = "Column::Group",
        to = "super::auto_role_group::Column::Name",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AutoRoleGroup,
}

impl Related<super::auto_role_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AutoRoleGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
