//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::{
    auto_role::Entity as AutoRole,
    auto_role_group::Entity as AutoRoleGroup,
    member::Entity as Member,
    xp_channel::Entity as XpChannel,
    xp_role::Entity as XpRole,
};
